# Generated by Django 3.1.4 on 2021-01-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extracurricular_or_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='month_completed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='related_link1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='related_link2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skill1',
            field=models.CharField(blank=True, choices=[('r', 'R'), ('python', 'Python'), ('scraping', 'Web Scraping'), ('django', 'Django'), ('rmd', 'Markdown'), ('tableau', 'Tableau')], max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='skill2',
            field=models.CharField(blank=True, choices=[('r', 'R'), ('python', 'Python'), ('scraping', 'Web Scraping'), ('django', 'Django'), ('rmd', 'Markdown'), ('tableau', 'Tableau')], max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='takeaway1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='takeaway2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
