# Generated by Django 2.1.1 on 2021-01-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210111_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='best_accuracy',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
