# Generated by Django 2.1.1 on 2021-01-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_best_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='related_img1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='related_img2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='related_title1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='related_title2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
