# Generated by Django 2.1.1 on 2021-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20210115_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill1',
            field=models.CharField(blank=True, choices=[('R', 'r'), ('Python', 'python'), ('Web Scraping', 'scraping'), ('Django', 'django'), ('Markdown', 'rmd'), ('Tableau', 'tableau')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='skill2',
            field=models.CharField(blank=True, choices=[('R', 'r'), ('Python', 'python'), ('Web Scraping', 'scraping'), ('Django', 'django'), ('Markdown', 'rmd'), ('Tableau', 'tableau')], max_length=20),
        ),
    ]
