# Generated by Django 2.1.1 on 2021-01-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210115_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='related_img3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='related_link3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='related_title3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='skill3',
            field=models.CharField(blank=True, choices=[('R', 'r'), ('Python', 'python'), ('Web Scraping', 'scraping'), ('Django', 'django'), ('Markdown', 'rmd'), ('Tableau', 'tableau')], max_length=20),
        ),
    ]
