# Generated by Django 2.1.1 on 2021-01-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210115_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('pk', 'title')},
        ),
        migrations.AlterField(
            model_name='job',
            name='skill1',
            field=models.CharField(blank=True, choices=[('R', 'r'), ('Python', 'python'), ('Web Scraping', 'scraping'), ('Django', 'django'), ('Markdown', 'rmd'), ('Tableau', 'tableau'), ('Machine Learning', 'machine learning')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='skill2',
            field=models.CharField(blank=True, choices=[('R', 'r'), ('Python', 'python'), ('Web Scraping', 'scraping'), ('Django', 'django'), ('Markdown', 'rmd'), ('Tableau', 'tableau'), ('Machine Learning', 'machine learning')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='skill3',
            field=models.CharField(blank=True, choices=[('R', 'r'), ('Python', 'python'), ('Web Scraping', 'scraping'), ('Django', 'django'), ('Markdown', 'rmd'), ('Tableau', 'tableau'), ('Machine Learning', 'machine learning')], max_length=20),
        ),
    ]
