# Generated by Django 2.1.1 on 2021-01-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_regatta_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='regatta_model',
        ),
    ]
